routes/web.php
            Route::get('invoices', 'InvoiceController@index')->name('invoices');
            Route::get('invoices/{invoice}', 'InvoiceController@show')
                ->name('patient.invoices.show')->where('invoice', '[0-9]+');
            Route::get('invoices/{invoice}/pdf', 'InvoiceController@convertToPdf')
                ->where('invoice', '[0-9]+');
            Route::get('bills', 'BillController@index')->name('employee.bills.index')->middleware('modules');
            Route::get('bills/{bill}', 'BillController@show')
                ->name('employee.bills.show')->where('bill', '[0-9]+');
            Route::get('bills/{bill}/pdf', 'BillController@convertToPdf')
                ->where('bill', '[0-9]+');
        });
    });

    Route::group(['middleware' => ['role:Admin|Doctor|Case Manager|Receptionist|Secretary']], function () {
        Route::get('patient-admissions/{patient_admission}', 'PatientAdmissionController@show')
            ->name('patient-admissions.show')->where('patient_admission', '[0-9]+');
        Route::get('patient-admissions-show/{patient_admission}', 'PatientAdmissionController@showModal')
            ->name('patient-admissions.show.modal')->where('patient_admission', '[0-9]+');
        Route::post('patient-admissions', 'PatientAdmissionController@store')->name('patient-admissions.store');
        Route::get('patient-admissions/create', 'PatientAdmissionController@create')->name('patient-admissions.create');
        Route::delete('patient-admissions/{patient_admission}', 'PatientAdmissionController@destroy')
            ->name('patient-admissions.destroy');
        Route::patch('patient-admissions/{patient_admission}', 'PatientAdmissionController@update')
            ->name('patient-admissions.update');
        Route::get('patient-admissions/{patient_admission}/edit', 'PatientAdmissionController@edit')
            ->name('patient-admissions.edit');
        Route::post('patient-admissions/{id}/active-deactive', 'PatientAdmissionController@activeDeactiveStatus');
    });

    Route::group(['middleware' => ['role:Admin|Doctor']], function () {
        Route::resource('document-types', 'DocumentTypeController')->parameters(['document-types' => 'documentType']);
        Route::get('document-types',
            'DocumentTypeController@index')->name('document-types.index')->middleware('modules');

        Route::resource('schedules', 'ScheduleController')->parameters(['schedules' => 'schedule']);
        Route::get('schedules', 'ScheduleController@index')->name('schedules.index')->middleware('modules');

        Route::resource('death-reports', 'DeathReportController')->parameters(['death-reports' => 'deathReport']);
        Route::get('death-reports', 'DeathReportController@index')->name('death-reports.index')->middleware('modules');

        Route::resource('birth-reports', 'BirthReportController')->parameters(['birth-reports' => 'birthReport']);
        Route::get('birth-reports', 'BirthReportController@index')->name('birth-reports.index')->middleware('modules');

        Route::resource('operation-reports',
            'OperationReportController')->parameters(['operation-reports' => 'operationReport']);
        Route::get('operation-reports',
            'OperationReportController@index')->name('operation-reports.index')->middleware('modules');

        Route::resource('investigation-reports',
            'InvestigationReportController')->parameters(['investigation-reports' => 'investigationReport']);
        Route::get('investigation-reports',
            'InvestigationReportController@index')->name('investigation-reports.index')->middleware('modules');

        // Route for Prescription
        Route::resource('prescriptions', 'PrescriptionController');
        Route::get('prescriptions/{id}/view', 'PrescriptionController@prescriptionsView');
        Route::get('prescription-pdf/{id}', 'PrescriptionController@convertToPDF')->name('prescriptions.pdf');
        Route::post('prescription-medicine', 'PrescriptionController@prescreptionMedicineStore')->name('prescription.medicine.store');
        Route::get('prescriptions-show-modal/{id}',
            'PrescriptionController@showModal')->name('prescriptions.show.modal');
        Route::get('prescriptions', 'PrescriptionController@index')->name('prescriptions.index')->middleware('modules');
        Route::post('prescriptions/{prescription}/active-deactive', 'PrescriptionController@activeDeactiveStatus');

        //Route for Vaccinations
        Route::resource('vaccinations', 'VaccinationController')->middleware('modules');

        //Route for Vaccinated Patients
        Route::get('vaccinations', 'VaccinationController@index')->name('vaccinations.index')->middleware('modules');
        Route::post('vaccinations', 'VaccinationController@store')->name('vaccinations.store');
        Route::get('vaccinations/create', 'VaccinationController@create')->name('vaccinations.create');
        Route::get('vaccinations/{vaccination}', 'VaccinationController@show')->name('vaccinations.show');
        Route::delete('vaccinations/{vaccination}', 'VaccinationController@destroy')->name('vaccinations.destroy');
        Route::post('vaccinations/{vaccination}/update', 'VaccinationController@update')->name('vaccination.update');
        Route::get('vaccinations/{vaccination}/edit', 'VaccinationController@edit')->name('vaccinations.edit');
        Route::get('export-vaccinations', 'VaccinationController@vaccinationsExport')->name('vaccinations.excel');

        //Route for Vaccinated Patients
        Route::get('vaccinated-patients',
            'VaccinatedPatientController@index')->name('vaccinated-patients.index')->middleware('modules');
        Route::post('vaccinated-patients', 'VaccinatedPatientController@store')->name('vaccinated-patients.store');
        Route::get('vaccinated-patients/create',
            'VaccinatedPatientController@create')->name('vaccinated-patients.create');
        Route::get('vaccinated-patients/{vaccinatedPatient}',
            'VaccinatedPatientController@show')->name('vaccinated-patients.show');
        Route::delete('vaccinated-patients/{vaccinatedPatient}',
            'VaccinatedPatientController@destroy')->name('vaccinated-patients.destroy');
        Route::post('vaccinated-patients/{vaccinatedPatient}/update',
            'VaccinatedPatientController@update')->name('vaccinated-patients.update');
        Route::get('vaccinated-patients/{vaccinatedPatient}/edit',
            'VaccinatedPatientController@edit')->name('vaccinated-patients.edit');
        Route::get('export-vaccinated-patients', 'VaccinatedPatientController@vaccinatedPatientExport')
            ->name('vaccinated-patients.excel');
    });

    Route::group(['middleware' => ['role:Admin|Secretary|Doctor|Nurse|Receptionist|MedTech|Pharmacist|Case Manager']],
        function () {
            Route::get('employee-payrolls/{employeePayroll}',
                'EmployeePayrollController@show')->where('employeePayroll', '[0-9]+');
            Route::get('employee-payrolls-show/{employeePayroll}',
                'EmployeePayrollController@showModal')->where('employeePayroll',
                '[0-9]+')->name('employee-payrolls.show.modal');
        });

    Route::group(['middleware' => ['role:Admin|Secretary|Receptionist']], function () {

        //services routes
        Route::resource('services', 'ServiceController')->parameters(['services' => 'service']);
        Route::get('services', 'ServiceController@index')->name('services.index')->middleware('modules');
        Route::post('services/{service_id}/active-deactive', 'ServiceController@activeDeActiveService');
    });

    Route::group(['middleware' => ['role:Admin|Secretary']], function () {
        Route::resource('accounts', 'AccountController')->parameters(['accounts' => 'account']);
        Route::get('accounts', 'AccountController@index')->name('accounts.index')->middleware('modules');
        Route::post('accounts/{account}/active-deactive', 'AccountController@activeDeactiveAccount');

        Route::get('employee-payrolls',
            'EmployeePayrollController@index')->name('employee-payrolls.index')->middleware('modules');
        Route::post('employee-payrolls', 'EmployeePayrollController@store')->name('employee-payrolls.store');
        Route::get('employee-payrolls/create', 'EmployeePayrollController@create')->name('employee-payrolls.create');
        Route::delete('employee-payrolls/{employeePayroll}', 'EmployeePayrollController@destroy')
            ->name('employee-payrolls.destroy');
        Route::patch('employee-payrolls/{employeePayroll}', 'EmployeePayrollController@update')
            ->name('employee-payrolls.update');
        Route::get('employee-payrolls/{employeePayroll}/edit', 'EmployeePayrollController@edit')
            ->name('employee-payrolls.edit');

        Route::resource('invoices', 'InvoiceController')->parameters(['invoices' => 'invoice']);
        Route::get('invoices', 'InvoiceController@index')->name('invoices.index')->middleware('modules');
        Route::post('invoices/{invoice}', 'InvoiceController@update');
        Route::get('invoices/{invoice}/pdf', 'InvoiceController@convertToPdf')->name('invoices.pdf');

        Route::resource('payments', 'PaymentController');
        Route::get('payments-show-modal/{payment}', 'PaymentController@showModal')->name('payments.show.modal');
        Route::get('payments', 'PaymentController@index')->name('payments.index')->middleware('modules');
        Route::get('export-payments', 'PaymentController@paymentExport')->name('payments.excel');

        // Route for Payment Reports
        Route::get('payment-reports', 'PaymentReportController@index')->name('payment.reports')->middleware('modules');

        Route::resource('bills', 'BillController');
        Route::get('bills', 'BillController@index')->name('bills.index')->middleware('modules');
        Route::post('bills/{bill}', 'BillController@update');

app/Http/Controllers/InvestigationReportController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateInvestigationReportRequest;
use App\Http\Requests\UpdateInvestigationReportRequest;
use App\Models\Document;
use App\Models\InvestigationReport;
use App\Models\Patient;
use App\Models\User;
use App\Queries\InvestigationReportDataTable;
use App\Repositories\InvestigationReportRepository;
use Carbon\Carbon;
use DataTables;
use Exception;
use Flash;
use Illuminate\Contracts\Filesystem\FileNotFoundException;
use Illuminate\Contracts\Routing\ResponseFactory;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Routing\Redirector;
use Illuminate\View\View;
use Spatie\MediaLibrary\MediaCollections\Models\Media;
use Storage;
use Str;

class InvestigationReportController extends AppBaseController
{
    /** @var InvestigationReportRepository */
    private $investigationReportRepository;

    public function __construct(InvestigationReportRepository $investigationReportRepo)
    {
        $this->investigationReportRepository = $investigationReportRepo;
    }

    /**
     * Display a listing of the InvestigationReport.
     *
     * @param  Request  $request
     *
     * @throws Exception
     *
     * @return Factory|View
     */
    public function index()
    {
        $data['statusArr'] = InvestigationReport::STATUS_ARR;

        return view('investigation_reports.index', $data);
    }

    /**
     * Show the form for creating a new InvestigationReport.
     *
     * @return Factory|View
     */
    public function create()
    {
        $status = InvestigationReport::STATUS;
        $patients = $this->investigationReportRepository->getPatients();
        $doctors = $this->investigationReportRepository->getDoctors();

        return view('investigation_reports.create', compact('status', 'patients', 'doctors'));
    }

    /**
     * Store a newly created InvestigationReport in storage.
     *
     * @param  CreateInvestigationReportRequest  $request
     *
     * @return RedirectResponse|Redirector
     */
    public function store(CreateInvestigationReportRequest $request)
    {
        $input = $request->all();
        $patientId = Patient::with('patientUser')->whereId($input['patient_id'])->first();
        $birthDate = $patientId->patientUser->dob;
        $reportDate = Carbon::parse($input['date'])->toDateString();
        if (! empty($birthDate) && $reportDate < $birthDate) {
            Flash::error('Investigation report date should not be smaller than patient birth date.');

            return redirect()->back()->withInput($input);
        }
        $this->investigationReportRepository->store($input);
        Flash::success(__('messages.investigation_report.investigation_report') . ' ' . __('messages.common.saved_successfully'));

        return redirect(route('investigation-reports.index'));
    }

    /**
     * @param  InvestigationReport  $investigationReport
     *
     * @return Factory|RedirectResponse|Redirector|View
     */
    public function show(InvestigationReport $investigationReport)
    {
        $investigationReport = $this->investigationReportRepository->find($investigationReport->id);
        if (empty($investigationReport)) {
            Flash::error('Investigation Report not found');

            return redirect(route('investigation-reports.index'));
        }

        return view('investigation_reports.show')->with('investigationReport', $investigationReport);
    }

    /**
     * Show the form for editing the specified InvestigationReport.
     *
     * @param  InvestigationReport  $investigationReport
     *
     * @return Factory|View
     */
    public function edit(InvestigationReport $investigationReport)
    {
        $status = InvestigationReport::STATUS;
        $patients = $this->investigationReportRepository->getPatients();
        $doctors = $this->investigationReportRepository->getDoctors();
        $fileExt = pathinfo($investigationReport->attachment_url, PATHINFO_EXTENSION);

        return view('investigation_reports.edit',
            compact('investigationReport', 'status', 'patients', 'doctors', 'fileExt'));
    }

    /**
     * Update the specified InvestigationReport in storage.
     *
     * @param  InvestigationReport  $investigationReport
     * @param  UpdateInvestigationReportRequest  $request
     *
     * @return RedirectResponse|Redirector
     */
    public function update(InvestigationReport $investigationReport, UpdateInvestigationReportRequest $request)
    {
        if (empty($investigationReport)) {
            Flash::error('Investigation Report not found');

            return redirect(route('investigation-reports.index'));
        }
        $input = $request->all();
        $patientId = Patient::with('patientUser')->whereId($input['patient_id'])->first();
        $birthDate = $patientId->patientUser->dob;
        $reportDate = Carbon::parse($input['date'])->toDateString();
        if (! empty($birthDate) && $reportDate < $birthDate) {
            Flash::error(__('messages.investigation_report.birth_date_validation'));

            return redirect()->back()->withInput($input);
        }
        $this->investigationReportRepository->update($input, $investigationReport->id);
        Flash::success(__('messages.investigation_report.investigation_report') . ' ' . __('messages.common.updated_successfully'));

        return redirect(route('investigation-reports.index'));
    }

    /**
     * Remove the specified InvestigationReport from storage.
     *
     * @param  InvestigationReport  $investigationReport
     *
     * @throws Exception
     *
     * @return JsonResponse
     */
    public function destroy(InvestigationReport $investigationReport)
    {
        $investigationReport->delete();

        return $this->sendSuccess(__('messages.investigation_report.investigation_report') . ' ' . __('messages.common.deleted_successfully'));
    }

    /**
     * @param  InvestigationReport  $investigationReport
     *
     * @throws FileNotFoundException
     *
     * @return ResponseFactory|\Illuminate\Http\Response
     */
    public function downloadMedia(InvestigationReport $investigationReport)
    {
        /** @var Media $documentMedia */
        $documentMedia = $investigationReport->media[0];
        $documentPath = $documentMedia->getPath();
        if (config('app.media_disc') === 'public') {
            $documentPath = (Str::after($documentMedia->getUrl(), '/uploads'));
        }

        $file = Storage::disk(config('app.media_disc'))->get($documentPath);

        $headers = [
            'Content-Type'        => $investigationReport->media[0]->mime_type,
            'Content-Description' => 'File Transfer',
            'Content-Disposition' => "attachment; filename={$investigationReport->media[0]->file_name}",
            'filename'            => $investigationReport->media[0]->file_name,
        ];

        return response($file, 200, $headers);
    }
}

resources/views/investigation_reports/action.blade.php
<div class="d-flex align-items-center">
    <a href="{{ url('investigation-reports'.'/'.$row->id.'/edit') }}" title="{{__('messages.common.edit') }}"
       class="btn px-1 text-primary fs-3 ps-0">
        <i class="fa-solid fa-pen-to-square"></i>
    </a>
    <a href="javascript:void(0)" title="{{__('messages.common.delete')}}" data-id="{{ $row->id }}"
       class="deleteInvestigationBtn btn px-1 text-danger fs-3 pe-0" wire:key="{{$row->id}}">
        <i class="fa-solid fa-trash"></i>
    </a>
</div>

resources/views/investigation_reports/add-button.blade.php
<a href="{{ route('investigation-reports.create') }}"
   class="btn btn-primary">{{ __('messages.investigation_report.new_investigation_report') }}</a>

resources/views/investigation_reports/create.blade.php
@extends('layouts.app')
@section('title')
    {{ __('messages.investigation_report.new_investigation_report') }}
@endsection
@section('header_toolbar')
    <div class="container-fluid">
        <div class="d-md-flex align-items-center justify-content-between mb-7">
            <h1 class="mb-0">@yield('title')</h1>
            <a href="{{ route('investigation-reports.index') }}"
               class="btn btn-outline-primary">{{ __('messages.common.back') }}</a>
        </div>
    </div>
@endsection
@section('content')
    <div class="container-fluid">
        <div class="d-flex flex-column">
            <div class="row">
                <div class="col-12">
                    @include('layouts.errors')
                </div>
            </div>
            <div class="card">
                <div class="card-body p-12">
                    {{ Form::open(['route' => 'investigation-reports.store', 'files' => 'true', 'id' => 'createInvestigationForm']) }}

                    @include('investigation_reports.fields')

                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </div>
@endsection
{{-- JS File :- assets/js/investigation_reports/create-edit.js --}}

resources/views/investigation_reports/edit.blade.php
@extends('layouts.app')
@section('title')
    {{ __('messages.investigation_report.edit_investigation_report') }}
@endsection
@section('header_toolbar')
    <div class="container-fluid">
        <div class="d-md-flex align-items-center justify-content-between mb-7">
            <h1 class="mb-0">@yield('title')</h1>
            <a href="{{ route('investigation-reports.index') }}"
               class="btn btn-outline-primary">{{ __('messages.common.back') }}</a>
        </div>
    </div>
@endsection
@section('content')
    <div class="container-fluid">
        <div class="d-flex flex-column">
            <div class="row">
                <div class="col-12">
                    @include('layouts.errors')
                </div>
            </div>
            <div class="card">
                <div class="card-body p-12">
                    {{ Form::model($investigationReport, ['route' => ['investigation-reports.update', $investigationReport->id], 'method' => 'patch', 'files' => 'true', 'id' => 'editInvestigationForm']) }}

                    @include('investigation_reports.edit_fields')

                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </div>
@endsection
{{-- JS File :- assets/js/investigation_reports/create-edit.js --}}

resources/views/investigation_reports/edit_fields.blade.php
<div class="row">
    <div class="col-md-4">
        <div class="form-group mb-5">
            {{ Form::label('title', __('messages.investigation_report.title').(':'), ['class' => 'form-label']) }}
            <span class="required"></span>
            {{ Form::text('title', null, ['class' => 'form-control','required']) }}
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group mb-5">
            {{ Form::label('patient_id', __('messages.investigation_report.patient').(':'), ['class' => 'form-label']) }}
            <span class="required"></span>
            {{ Form::select('patient_id',$patients, null, ['class' => 'form-select','required','id' => 'editInvestigationPatientId','placeholder'=>'Select Patient','data-control' => 'select2']) }}
        </div>
    </div>
    @if(Auth::user()->hasRole('Doctor'))
        <input type="hidden" name="doctor_id" value="{{ Auth::user()->owner_id }}">
    @else
        <div class="col-md-4">
            <div class="form-group mb-5">
                {{ Form::label('doctor_id', __('messages.investigation_report.doctor').(':'), ['class' => 'form-label']) }}
                <span class="required"></span>
                {{ Form::select('doctor_id',$doctors, null, ['class' => 'form-select','required','id' => 'editInvestigationDoctorId','placeholder'=>'Select Doctor','data-control' => 'select2']) }}
            </div>
        </div>
    @endif
    <div class="col-md-4">
        <div class="form-group investigation-report-date mb-5">
            {{ Form::label('date', __('messages.investigation_report.date').(':'), ['class' => 'form-label']) }}
            <span class="required"></span>
            {{ Form::text('date', null, ['class' => (getLoggedInUser()->thememode ? 'bg-light form-control' : 'bg-white form-control'),'id' => 'editInvestigationDate','required','autocomplete' => 'off']) }}
        </div>
    </div>
    <div class="form-group col-md-4 mb-5">
        <div class="row2" io-image-input="true">
            {{ Form::label('image',__('messages.common.profile').(':'), ['class' => 'form-label']) }}
            <div class="d-block">
                <div class="image-picker">
                    <div class="image previewImage" id="editInvestigationPreviewImage"
                         style="background-image: url('{{ $investigationReport->attachment_url ?? asset('assets/img/default_image.jpg')}}')">
                    <span class="picker-edit rounded-circle text-gray-500 fs-small" title="{{ __('messages.investigation_report.attachment') }}">
                                    <label>
                                    <i class="fa-solid fa-pen" id="profileImageIcon"></i>
                                        <input type="file" id="editAccountantProfileImage" name="attachment"
                                               class="image-upload d-none profileImage"
                                               accept=".png, .jpg, .jpeg, .gif"/>
                                        <input type="hidden" name="avatar_remove"/>
                                    </label>
                                </span>
                    </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group mb-5">
                {{ Form::label('status', __('messages.common.status').(':'), ['class' => 'form-label']) }}
                <span class="required"></span>
                {{ Form::select('status', $status, null, ['id' => 'editInvestigationStatus','class' => 'form-select','required','data-control' => 'select2']) }}
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group mb-5">
                {{ Form::label('description', __('messages.investigation_report.description').(':'), ['class' => 'form-label']) }}
                {{ Form::textarea('description', null, ['class' => 'form-control col-sm-6 d-flex flex-column mb-md-10 mb-5']) }}
            </div>
        </div>
        <div class="d-flex justify-content-end">
            {{ Form::submit(__('messages.common.save'), ['class' => 'btn btn-primary me-2']) }}
            <a href="{{ route('investigation-reports.index') }}"
               class="btn btn-secondary me-2">{{ __('messages.common.cancel') }}</a>
        </div>
    </div>

resources/views/investigation_reports/fields.blade.php
<div class="row">
    <div class="col-md-4">
        <div class="form-group mb-5">
            {{ Form::label('title', __('messages.investigation_report.title').(':'), ['class' => 'form-label']) }}
            <span class="required"></span>
            {{ Form::text('title', null, ['class' => 'form-control','required']) }}
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group mb-5">
            {{ Form::label('patient_id', __('messages.investigation_report.patient').(':'), ['class' => 'form-label']) }}
            <span class="required"></span>
            {{ Form::select('patient_id',$patients, null, ['class' => 'form-select','required','id' => 'investigationPatientId','placeholder'=>'Select Patient','data-control' => 'select2']) }}
        </div>
    </div>
    @if(Auth::user()->hasRole('Doctor'))
        <input type="hidden" name="doctor_id" value="{{ Auth::user()->owner_id }}">
    @else
        <div class="col-md-4">
            <div class="form-group mb-5">
                {{ Form::label('doctor_id', __('messages.investigation_report.doctor').(':'), ['class' => 'form-label']) }}
                <span class="required"></span>
                {{ Form::select('doctor_id',$doctors, null, ['class' => 'form-select','required','id' => 'investigationDoctorId','placeholder'=>'Select Doctor','data-control' => 'select2']) }}
            </div>
        </div>
    @endif
    <div class="col-md-4">
        <div class="form-group investigation-report-date mb-5">
            {{ Form::label('date', __('messages.investigation_report.date').(':'), ['class' => 'form-label']) }}
            <span class="required"></span>
            {{ Form::text('date', null, ['class' => (getLoggedInUser()->thememode ? 'bg-light form-control' : 'bg-white form-control'),'id' => 'investigationDate','required','autocomplete' => 'off']) }}
        </div>
    </div>
    <div class="form-group col-md-4 mb-5">
        <div class="row2" io-image-input="true">
            {{ Form::label('image',__('messages.investigation_report.attachment').(':'), ['class' => 'form-label']) }}
            <div class="d-block">
                <?php
                $style = 'style=';
                $background = 'background-image:';
                ?>

                <div class="image-picker">
                    <div class="image previewImage" id="investigationPreviewImage"
                    {{$style}}"{{$background}} url({{ asset('assets/img/default_image.png')}}">
                    <span class="picker-edit rounded-circle text-gray-500 fs-small" title="{{ __('messages.investigation_report.attachment') }}">
                        <label>
                        <i class="fa-solid fa-pen" id="profileImageIcon"></i>
                            <input type="file" id="investigationAttachment" name="attachment"
                                   class="image-upload d-none profileImage"
                                   accept=".png, .jpg, .jpeg, .gif"/>
                            <input type="hidden" name="avatar_remove"/>
                        </label>
                    </span>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="col-md-4">
    <div class="form-group mb-5">
        {{ Form::label('status', __('messages.common.status').(':'), ['class' => 'form-label']) }}
        <span class="required"></span>
        {{ Form::select('status', $status, null, ['id' => 'investigationStatus','class' => 'form-select','required','data-control' => 'select2']) }}
    </div>
</div>
<div class="col-md-12">
    <div class="form-group mb-5">
        {{ Form::label('description', __('messages.investigation_report.description').(':'), ['class' => 'form-label']) }}
        {{ Form::textarea('description', null, ['class' => 'form-control']) }}
    </div>
</div>
<div class="d-flex justify-content-end">
    {{ Form::submit(__('messages.common.save'), ['class' => 'btn btn-primary me-2']) }}
    <a href="{{ route('investigation-reports.index') }}"
       class="btn btn-secondary me-2">{{ __('messages.common.cancel') }}</a>
</div>
</div>

resources/views/investigation_reports/filter-button.blade.php
<div class="ms-0 ms-md-2" wire:ignore>
    <div class="dropdown d-flex align-items-center me-4 me-md-5">
        <button
                class="btn btn btn-icon btn-primary text-white dropdown-toggle hide-arrow ps-2 pe-0"
                type="button"  data-bs-auto-close="outside"
                data-bs-toggle="dropdown" aria-expanded="false"
                id="investigationFilterBtn">
            <i class='fas fa-filter'></i>
        </button>
        <div class="dropdown-menu py-0" aria-labelledby="investigationFilterBtn">
            <div class="text-start border-bottom py-4 px-7">
                <h3 class="text-gray-900 mb-0">{{ __('messages.common.filter_options') }}</h3>
            </div>
            <div class="p-5">
                <div class="mb-5">
                    <label for="exampleInputSelect2" class="form-label">{{ __('messages.common.status').':' }}</label>
                    {{ Form::select('investigation_head', $filterHeads[0], null,['id' => 'investigationHead', 'data-control' =>'select2', 'class' => 'form-select status-filter']) }}
                </div>
                <div class="d-flex justify-content-end">
                    <button type="reset" id="investigationResetFilter" class="btn btn-secondary">{{ __('messages.common.reset') }}</button>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/investigation_reports/index.blade.php
@extends('layouts.app')
@section('title')
    {{ __('messages.investigation_report.investigation_reports') }}
@endsection
@section('content')
    <div class="container-fluid">
        <div class="d-flex flex-column">
            @include('flash::message')
            {{Form::hidden('investigationReportUrl',url('investigation-reports'),['id'=>'indexInvestigationReportUrl'])}}
            {{ Form::hidden('investigation_report', __('messages.investigation_report.investigation_report'), ['id' => 'investigationReport']) }}
            <livewire:investigation-report-table/>
            @include('partials.page.templates.templates')
        </div>
    </div>
@endsection
{{-- JS File :- assets/js/investigation_reports/investigation_reports.js --}}